"""Generate the release artifacts. Spec sections 9.3.1, 9.3.3 and 9.4.

Run it with ``make release-core``, and with ``--check`` to find out whether the
artifacts on disk are the ones this tree would produce without writing
anything.

Four files come out of one generation, and they are four views of a single
document:

``src/techtree/resources/release/release-core.json``
    The copy the wheel ships and the CLI reads. It lives inside the package
    because spec section 9.6 requires the wheel to contain the exact
    ReleaseCore, and a file outside the package cannot be in a wheel.

``release/release-core.json``
    Byte-identical, at the path spec section 9.4 gives it. This is the copy
    other repositories take: the plugin embeds these bytes and the website
    wraps them. Both copies are written by this tool and compared by
    ``make generated-check``, so the two cannot drift apart.

``release/release-core.schema.json``
    What a consumer in another language validates the document against.

``release/build-info.json``
    Which inputs produced which bytes.

The founder-owned half of the release is not generated. It is read from
``release/release-inputs.json``, which is edited by hand exactly once per
release, so that regenerating in a throwaway copy of the repository produces
the same bytes as regenerating here.
"""

from __future__ import annotations

import argparse
import json
import sys
import tomllib
from collections.abc import Mapping
from pathlib import Path
from typing import Final

from techtree.canonical import sha256_digest_bytes
from techtree.models.base import Digest
from techtree.release.document import (
    RELEASE_CORE_FILENAME,
    RELEASE_RESOURCE_DIRECTORY,
    document_digest,
    parse_release_inputs,
    render_document,
    render_release_core,
)
from techtree.release.generate import (
    build_info_document,
    build_release_core,
    packaged_sources,
)
from techtree.release.models import ReleaseCore

REPOSITORY_ROOT: Final = Path(__file__).resolve().parent.parent

#: The staging directory other repositories copy from. Spec section 9.4.
RELEASE_DIRECTORY: Final = REPOSITORY_ROOT / "release"
#: The copy that goes into the wheel.
PACKAGED_DIRECTORY: Final = (
    REPOSITORY_ROOT / "src" / "techtree" / "resources" / RELEASE_RESOURCE_DIRECTORY
)

INPUTS_FILENAME: Final = "release-inputs.json"
SCHEMA_FILENAME: Final = "release-core.schema.json"
BUILD_INFO_FILENAME: Final = "build-info.json"

#: The dialect and naming ``tools/export_schemas.py`` publishes under, so a
#: consumer sees one schema convention across the whole project.
JSON_SCHEMA_DIALECT: Final = "https://json-schema.org/draft/2020-12/schema"
SCHEMA_ID_BASE: Final = "https://schemas.techtree.dev/release"


def release_artifacts() -> dict[Path, bytes]:
    """Return every generated release file and the bytes it should hold."""
    inputs_bytes = (RELEASE_DIRECTORY / INPUTS_FILENAME).read_bytes()
    inputs = parse_release_inputs(inputs_bytes)
    core = build_release_core(inputs, packaged_sources())
    core_bytes = render_release_core(core)
    schema_bytes = schema_document(core)

    artifacts: dict[Path, bytes] = {
        PACKAGED_DIRECTORY / RELEASE_CORE_FILENAME: core_bytes,
        RELEASE_DIRECTORY / RELEASE_CORE_FILENAME: core_bytes,
        RELEASE_DIRECTORY / SCHEMA_FILENAME: schema_bytes,
    }
    artifacts[RELEASE_DIRECTORY / BUILD_INFO_FILENAME] = render_document(
        build_info_document(
            inputs_digest=sha256_digest_bytes(inputs_bytes),
            pyproject_version=pyproject_version(),
            core=core,
            artifacts=_digests(artifacts),
        )
    )
    return artifacts


def pyproject_version() -> str:
    """Return the version this source tree declares for the CLI package.

    Read from ``pyproject.toml`` rather than from installed distribution
    metadata: the generated bytes have to be a function of the tree, not of
    whether the tree happens to be installed in the environment running the
    generator.
    """
    with (REPOSITORY_ROOT / "pyproject.toml").open("rb") as handle:
        return str(tomllib.load(handle)["project"]["version"])


def schema_document(core: ReleaseCore) -> bytes:
    """Return the published JSON Schema for the ReleaseCore document."""
    schema = type(core).model_json_schema(
        by_alias=True,
        ref_template="#/$defs/{model}",
        mode="validation",
    )
    document = {
        "$schema": JSON_SCHEMA_DIALECT,
        "$id": f"{SCHEMA_ID_BASE}/{SCHEMA_FILENAME}",
        **schema,
    }
    rendered = json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False)
    return f"{rendered}\n".encode()


def write(artifacts: Mapping[Path, bytes]) -> None:
    """Write every artifact, creating the directories they live in."""
    for path, data in sorted(artifacts.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)


def drift(artifacts: Mapping[Path, bytes]) -> list[str]:
    """Return the artifacts on disk that are not what this tree produces."""
    stale: list[str] = []
    for path, data in sorted(artifacts.items()):
        relative = path.relative_to(REPOSITORY_ROOT).as_posix()
        if not path.is_file():
            stale.append(f"{relative} is missing")
        elif path.read_bytes() != data:
            stale.append(f"{relative} is not what this source tree generates")
    return stale


def main(argv: list[str] | None = None) -> int:
    """Generate the release artifacts, or report that they are stale."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report drift and write nothing.",
    )
    arguments = parser.parse_args(argv)

    artifacts = release_artifacts()
    core_bytes = artifacts[RELEASE_DIRECTORY / RELEASE_CORE_FILENAME]

    if arguments.check:
        stale = drift(artifacts)
        for problem in stale:
            sys.stdout.write(f"release-core: {problem}\n")
        if stale:
            sys.stdout.write("release-core: run `make release-core`\n")
            return 1
        sys.stdout.write(
            f"release-core: {len(artifacts)} artifacts match this source tree\n"
        )
        return 0

    write(artifacts)
    sys.stdout.write(f"{document_digest(core_bytes)}\n")
    return 0


def _digests(artifacts: Mapping[Path, bytes]) -> dict[str, Digest]:
    return {
        path.relative_to(REPOSITORY_ROOT).as_posix(): sha256_digest_bytes(data)
        for path, data in artifacts.items()
    }


if __name__ == "__main__":
    raise SystemExit(main())
