"""Build the static engine bundle. Spec section 24.2.

The bundle under ``src/techtree/resources/engines/default/`` is generated, and
this is the only thing allowed to generate it. It writes the engine project
file with the exact Verifiers commit, runs ``uv lock`` to pin everything that
commit drags in, writes the descriptor with the version the lock resolved and
the reference package's source digest, and prints the resulting bundle digest.

``uv lock`` runs *here* and never on a user's machine. A participant's install
is ``uv sync --frozen`` against the lock this tool produced, which is what
makes two participants' engines the same engine.

Two things this tool deliberately does not do.

It does not copy the reference package. Spec section 8 puts the authoritative
source of the reference taskset inside the bundle already, so there is no
second copy to keep in step; the tool reads that tree, digests it, and refuses
to run if it is missing or malformed.

It does not touch the catalog. The engine bundle holds no Campaign, Climb,
DataPolicy, or catalog object at all, which is exactly why the generation order
in spec section 25 has no cycle in it.

Run it with ``make engine-bundle``. ``make generated-check`` runs it again in a
throwaway copy of the repository and fails on any drift, so every byte it
writes has to be a function of its inputs.
"""

from __future__ import annotations

import subprocess
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Final

from techtree.constants import (
    ENGINE_SCHEMA_VERSION,
    PINNED_VERIFIERS_REVISION,
    SUPPORTED_HOST_PLATFORMS,
)
from techtree.engines.bundle import (
    DEFAULT_ENGINE_NAME,
    DESCRIPTOR_FILENAME,
    ENGINE_TOOLS,
    PACKAGES_DIRECTORY,
    TOOLS_DIRECTORY,
    engine_bundle_digest,
    package_source_digest,
)
from techtree.fs import atomic_write_json, atomic_write_text
from techtree.models.engine import EngineDescriptor, EnginePackage

REPOSITORY_ROOT: Final = Path(__file__).resolve().parent.parent
ENGINE_ROOT: Final = (
    REPOSITORY_ROOT / "src" / "techtree" / "resources" / "engines" / DEFAULT_ENGINE_NAME
)

#: Decisions document 0001. Never a branch, a tag, or an unpinned range.
VERIFIERS_REPOSITORY: Final = "https://github.com/PrimeIntellect-ai/verifiers"
#: The reference taskset, spec section 22. Its distribution name is also its
#: Verifiers taskset id.
REFERENCE_PACKAGE: Final = "procedure-transfer-v1"
#: Spec section 20.3 installs with ``--python 3.12``; the engine project pins
#: the same interpreter series so the lock cannot resolve for anything else.
ENGINE_PYTHON_SERIES: Final = "3.12"
ENGINE_REQUIRES_PYTHON: Final = ">=3.12,<3.13"

LOCK_TIMEOUT_SECONDS: Final = 600.0


@dataclass(frozen=True)
class EnginePins:
    """Everything the engine project file is allowed to vary by."""

    verifiers_repository: str
    verifiers_revision: str
    reference_package: str
    requires_python: str


def write_engine_project(destination: Path, pins: EnginePins) -> None:
    """Write ``pyproject.toml`` with the exact Verifiers source.

    The reference package is an editable path dependency (decisions document
    0003 A8): the digested source tree in the bundle is what the engine
    imports, so what ran can be compared with what was published.
    """
    package_source = (
        f"{pins.reference_package} = {{ path = "
        f'"{PACKAGES_DIRECTORY}/{pins.reference_package}", editable = true }}'
    )
    verifiers_source = (
        f'verifiers = {{ git = "{pins.verifiers_repository}", '
        f'rev = "{pins.verifiers_revision}" }}'
    )
    document = f"""\
# The managed Techtree evaluation engine.
#
# Generated by tools/build_engine_bundle.py. Do not edit by hand: the file is
# part of the engine bundle digest, and `make generated-check` rewrites it in a
# throwaway tree and fails on any difference.

[project]
name = "techtree-engine-{DEFAULT_ENGINE_NAME}"
version = "0.1.0"
description = "Pinned Verifiers environment and reference tasksets for Techtree."
requires-python = "{pins.requires_python}"
dependencies = [
  "{pins.reference_package}",
  "verifiers",
]

[tool.uv]
# The engine project is an environment, not a distribution. Nothing installs it.
package = false

[tool.uv.sources]
{package_source}
{verifiers_source}
"""
    atomic_write_text(destination / "pyproject.toml", document, mode=0o644)


def run_uv_lock(destination: Path) -> None:
    """Generate the frozen lock for the engine project."""
    completed = subprocess.run(
        ["uv", "lock", "--project", str(destination)],
        capture_output=True,
        text=True,
        check=False,
        timeout=LOCK_TIMEOUT_SECONDS,
        stdin=subprocess.DEVNULL,
    )
    if completed.returncode != 0:
        raise SystemExit(
            f"uv lock failed ({completed.returncode}):\n{completed.stderr.strip()}"
        )


def locked_version(destination: Path, package: str) -> str:
    """Return the version ``uv lock`` resolved for one package."""
    document = tomllib.loads((destination / "uv.lock").read_text(encoding="utf-8"))
    for entry in document.get("package", []):
        if entry.get("name") == package:
            version = entry.get("version")
            if isinstance(version, str):
                return version
    raise SystemExit(f"uv.lock does not contain a version for {package}")


def declared_version(package_root: Path) -> str:
    """Return the version a shipped package declares in its own project file."""
    document = tomllib.loads(
        (package_root / "pyproject.toml").read_text(encoding="utf-8")
    )
    version = document.get("project", {}).get("version")
    if not isinstance(version, str):
        raise SystemExit(f"{package_root}/pyproject.toml declares no project version")
    return version


def build_engine_descriptor(destination: Path) -> EngineDescriptor:
    """Describe the bundle as it now stands on disk."""
    package_root = destination / PACKAGES_DIRECTORY / REFERENCE_PACKAGE
    return EngineDescriptor(
        schema_version=ENGINE_SCHEMA_VERSION,
        name=DEFAULT_ENGINE_NAME,
        python_version=ENGINE_PYTHON_SERIES,
        verifiers_version=locked_version(destination, "verifiers"),
        verifiers_revision=PINNED_VERIFIERS_REVISION,
        supported_hosts=list(SUPPORTED_HOST_PLATFORMS),
        packages=[
            EnginePackage(
                name=REFERENCE_PACKAGE,
                version=declared_version(package_root),
                source_digest=package_source_digest(package_root),
            )
        ],
    )


def write_engine_descriptor(destination: Path, descriptor: EngineDescriptor) -> None:
    """Write ``engine.json``."""
    atomic_write_json(destination / DESCRIPTOR_FILENAME, descriptor, mode=0o644)


def check_bundle_sources(destination: Path) -> None:
    """Refuse to build from an incomplete bundle tree."""
    package_root = destination / PACKAGES_DIRECTORY / REFERENCE_PACKAGE
    required = [
        package_root / "pyproject.toml",
        *(destination / TOOLS_DIRECTORY / tool for tool in ENGINE_TOOLS),
    ]
    missing = [
        str(path.relative_to(destination)) for path in required if not path.is_file()
    ]
    if missing:
        raise SystemExit(
            "the engine bundle is missing authored files: " + ", ".join(missing)
        )


def main() -> None:
    """Build the static bundle and print its digest."""
    destination = ENGINE_ROOT
    check_bundle_sources(destination)

    pins = EnginePins(
        verifiers_repository=VERIFIERS_REPOSITORY,
        verifiers_revision=PINNED_VERIFIERS_REVISION,
        reference_package=REFERENCE_PACKAGE,
        requires_python=ENGINE_REQUIRES_PYTHON,
    )
    write_engine_project(destination, pins)
    run_uv_lock(destination)
    write_engine_descriptor(destination, build_engine_descriptor(destination))

    sys.stdout.write(f"{engine_bundle_digest(destination)}\n")


if __name__ == "__main__":
    main()
